/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.metalurgicametodo.swing;

import com.br.metalurgicametodo.dao.FuncionarioDAO;
import com.br.metalurgicametodo.entidades.Funcionario;
import com.sun.javafx.geom.CubicApproximator;
import java.awt.Cursor;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author rds_d
 */
//classe responsavel por buscar cadastro de funcionario
public class Buscar_funcionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form Buscar_funcionario
     */
    public Buscar_funcionario() {
        initComponents();
    }
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    public static Funcionario  func = null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBuscarFuncionario = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        lblRE = new javax.swing.JLabel();
        jftRE = new javax.swing.JFormattedTextField();

        setClosable(true);
        setTitle("Buscar Funcionario");

        lblBuscarFuncionario.setText("Buscar Funcionario ");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblRE.setText("RE:");

        try {
            jftRE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftREActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBuscarFuncionario)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblRE)
                                .addGap(18, 18, 18)
                                .addComponent(jftRE, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblBuscarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRE)
                    .addComponent(jftRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnBuscar)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try{
            //verifica se se o usuario inseriu algum valor no campo de RE
        if (jftRE.getText().substring(0, 1).equals(" ")) {
            JOptionPane.showMessageDialog(null, "Por favor insira um RE");
        } else {
            func = new Funcionario();
            FuncionarioDAO funcDAO = new FuncionarioDAO();
            //busca um funcionario no banco atravez do texto adquirido no campo RE
            func = funcDAO.buscarPorRE(Integer.parseInt(jftRE.getText()));
            // verifica se o objeto de funcionario não esta vazio
            if (func != null) {
                //abre uma interface Swing de editar cadastro do funcionario
                EditarCadastroFuncionario edf = new EditarCadastroFuncionario();
                Tela_Principal.jdp_principal.add(edf);
                edf.setVisible(true);
                edf.setPosicao();
                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            }else
                //emiti uma mensagem pro usuario caso não encontre o funcionario no banco de dados
            {
                JOptionPane.showMessageDialog(null, "Funcionário não encontrado!!");
                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            }
        }
       }catch(Exception e )
       {
           // emiti uma mensagem de erro caso ocorra alguma exceção
           JOptionPane.showMessageDialog(null, "Erro ao buscar funcionário");
       }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jftREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftREActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField jftRE;
    private javax.swing.JLabel lblBuscarFuncionario;
    private javax.swing.JLabel lblRE;
    // End of variables declaration//GEN-END:variables
}
