/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.metalurgicametodo.swing;

import com.br.metalurgicametodo.dao.PessoaFisicaDAO;
import com.br.metalurgicametodo.dao.PessoaJuridicaDAO;
import com.br.metalurgicametodo.entidades.PessoaFisica;
import com.br.metalurgicametodo.entidades.PessoaJuridica;
import java.awt.Cursor;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Bruno
 */
//Classe responsavel por buscar cadastro de Cliente
public class BuscarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarCliente
     */
    public BuscarCliente() {
        initComponents();
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    public static PessoaFisica pF = null;
    public static PessoaJuridica pJ = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTipoPessoa = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rbtnFisica = new javax.swing.JRadioButton();
        rbtnJuridica = new javax.swing.JRadioButton();
        btnBuscar = new javax.swing.JButton();
        jftFisica = new javax.swing.JFormattedTextField();
        jftJuridica = new javax.swing.JFormattedTextField();

        setClosable(true);
        setTitle("Localizar Cliente");

        jLabel2.setText("Buscar por: ");

        btnGroupTipoPessoa.add(rbtnFisica);
        rbtnFisica.setText("CPF: ");
        rbtnFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFisicaActionPerformed(evt);
            }
        });

        btnGroupTipoPessoa.add(rbtnJuridica);
        rbtnJuridica.setText("CNPJ: ");
        rbtnJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnJuridicaActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        MaskFormatter mascaraCpf = null;
        try {
            jftFisica.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaraCpf = new MaskFormatter("###.###.###-##")));
            mascaraCpf.setPlaceholderCharacter('_');
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        MaskFormatter mascaraCnpj = null;
        try {
            jftJuridica.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaraCnpj = new MaskFormatter("##.###.###/####-##")));
            mascaraCnpj.setPlaceholderCharacter('_');
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnJuridica)
                            .addComponent(rbtnFisica)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jftFisica)
                            .addComponent(jftJuridica, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(btnBuscar)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnFisica)
                    .addComponent(jftFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnJuridica)
                    .addComponent(jftJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        //verifica se o radio button de cpf esta selecionado
        if (rbtnFisica.isSelected()) {
            //verifica se o campo não esta vazio
            // se estiver ira emitir uma mensagem pro usuario
            if (jftFisica.getText().substring(0, 1).equals(" ") || jftFisica.getText().substring(0, 1).equals("_")) {
                JOptionPane.showMessageDialog(null, "Por Favor insira um CPF!");
            } else {
                try {

                    pF = new PessoaFisica();
                    PessoaFisicaDAO pfDAO = new PessoaFisicaDAO();
                    // buscar uma pessoa fisica atravez do cpf inserido pelo usuario
                    pF = pfDAO.buscarCPF(jftFisica.getText());
                    // se apos a buscar a pessoa fisica estiver vazia , quer dizer que esse cpf não existe no sistema
                    // e então ira emitir uma mensagem pro usuario
                    if (pF != null) {
                        //apos verifica se a  Pessoa Fisica existe será aberto uma nova Interface Swing
                        VisualizarPessoaFisica vpf = new VisualizarPessoaFisica();
                        Tela_Principal.jdp_principal.add(vpf);
                        vpf.setVisible(true);
                        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                    } else {
                        JOptionPane.showMessageDialog(null, "CPF não encontrado. Por Favor digite um novo!");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro ao realizar a Operação de busca. Mensagem: " + e.getMessage());

                }
                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            }
            //verifica se o radio button de cnpj esta selecionado
        } else if (rbtnJuridica.isSelected()) {

            //verifica se o campo não esta vazio
            // se estiver ira emitir uma mensagem pro usuario
            if (jftJuridica.getText().substring(0, 1).equals(" ") || jftJuridica.getText().substring(0, 1).equals("_")) {
                JOptionPane.showMessageDialog(null, "Por favor insira um CNPJ!");
            } else {
                try {
                    PessoaJuridicaDAO pjDAO = new PessoaJuridicaDAO();

                    pJ = pjDAO.buscarCNPJ(jftJuridica.getText());
                //busca uma pessoa juridica no banco atravez do cnpj inserido pelo usuario

                    // se apos a buscar a pessoa juridicaestiver vazia , quer dizer que esse cnpj não existe no sistema
                    // e então ira emitir uma mensagem pro usuario
                    if (pJ != null) {
                        //apos verifica se a  Pessoa Juridica existe será aberto uma nova Interface Swing 
                        VisualizarPessoaJuridica vpj = new VisualizarPessoaJuridica();
                        Tela_Principal.jdp_principal.add(vpj);
                        vpj.setVisible(true);
                        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                    } else {
                        JOptionPane.showMessageDialog(null, "CPNJ não encontrado!!!");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro ao realizar a Operação de busca. Mensagem: " + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por Favor selecione um tipo de filtro");
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void rbtnFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFisicaActionPerformed
        jftFisica.setText("");
        jftJuridica.setText("");
        jftFisica.setEnabled(true);
        jftJuridica.setEnabled(false);

    }//GEN-LAST:event_rbtnFisicaActionPerformed

    private void rbtnJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnJuridicaActionPerformed
        jftFisica.setText("");
        jftJuridica.setText("");
        jftFisica.setEnabled(false);
        jftJuridica.setEnabled(true);
    }//GEN-LAST:event_rbtnJuridicaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.ButtonGroup btnGroupTipoPessoa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField jftFisica;
    private javax.swing.JFormattedTextField jftJuridica;
    private javax.swing.JRadioButton rbtnFisica;
    private javax.swing.JRadioButton rbtnJuridica;
    // End of variables declaration//GEN-END:variables
}
