/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.metalurgicametodo.swing;

import com.br.metalurgicametodo.dao.FuncionarioDAO;
import com.br.metalurgicametodo.entidades.Funcionario;
import java.awt.Cursor;
import java.awt.Dimension;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author rds_d
 */
public class EditarCadastroFuncionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditarCadastroFuncionario
     */
    //Classe utilizada para visualizar e editar funcionario
    public EditarCadastroFuncionario() {
        initComponents();
        //pega informaçoes do funcionario da classe de interface swing Buscar_funcionario
        func = new Funcionario();
        func = Buscar_funcionario.func;
        //insere todas as informaçoes de funcionarios nos campos de texto
        txtCargoFunc.setText(func.getCargo());
        txtLogin.setText(func.getLogin());
        txtNomefunc.setText(func.getNome());
        txtReFunc.setText(String.valueOf(func.getRe()));
        txtSenhaFunc.setText(func.getSenha());
        txtSenhaConfFunc.setText(func.getSenha());
    }
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    public static Funcionario func = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        lbl_nomeFunc = new javax.swing.JLabel();
        txtNomefunc = new javax.swing.JTextField();
        lbl_emailFunc = new javax.swing.JLabel();
        txtCargoFunc = new javax.swing.JTextField();
        lbl_senhaFunc = new javax.swing.JLabel();
        txtSenhaFunc = new javax.swing.JPasswordField();
        lbl_reFunc = new javax.swing.JLabel();
        txtReFunc = new javax.swing.JFormattedTextField();
        lbl_confirmeSenhaFunc = new javax.swing.JLabel();
        txtSenhaConfFunc = new javax.swing.JPasswordField();
        lbl_emailCon = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setClosable(true);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Funcionario"));

        lbl_nomeFunc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_nomeFunc.setText("Nome :");

        txtNomefunc.setEnabled(false);
        txtNomefunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomefuncActionPerformed(evt);
            }
        });

        lbl_emailFunc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_emailFunc.setText("Login:");

        txtCargoFunc.setEnabled(false);

        lbl_senhaFunc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_senhaFunc.setText("Senha:");

        txtSenhaFunc.setEnabled(false);

        lbl_reFunc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_reFunc.setText("RE:");

        txtReFunc.setEnabled(false);

        lbl_confirmeSenhaFunc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_confirmeSenhaFunc.setText("Confirme a Senha:");

        txtSenhaConfFunc.setEnabled(false);
        txtSenhaConfFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaConfFuncActionPerformed(evt);
            }
        });

        lbl_emailCon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_emailCon.setText("Cargo:");

        txtLogin.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_senhaFunc)
                    .addComponent(lbl_nomeFunc)
                    .addComponent(lbl_emailFunc))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomefunc)
                    .addComponent(txtSenhaFunc)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lbl_confirmeSenhaFunc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSenhaConfFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lbl_emailCon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCargoFunc))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lbl_reFunc)
                        .addGap(18, 18, 18)
                        .addComponent(txtReFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbl_reFunc)
                    .addComponent(txtNomefunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nomeFunc)
                    .addComponent(txtReFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_emailFunc)
                    .addComponent(lbl_emailCon)
                    .addComponent(txtCargoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_confirmeSenhaFunc)
                        .addComponent(txtSenhaConfFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_senhaFunc)
                        .addComponent(txtSenhaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir)
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomefuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomefuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomefuncActionPerformed

    private void txtSenhaConfFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaConfFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaConfFuncActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        //habilita os campos , e botões para alteraçoes
        txtCargoFunc.setEnabled(true);
        txtSenhaFunc.setEnabled(true);
        txtSenhaConfFunc.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnExcluir.setEnabled(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            // pega todas as informaçoes do funcionario alterado nos campos de texto
            func.setCargo(txtCargoFunc.getText());
            if (Arrays.equals(txtSenhaFunc.getPassword(), txtSenhaConfFunc.getPassword())) {
                func.setSenha(String.valueOf(txtSenhaFunc.getPassword()));
                FuncionarioDAO funcDAO = new FuncionarioDAO();
               // realiza a alteração de informaçoes do funcionario
                funcDAO.update(func);
                JOptionPane.showMessageDialog(null, "Funcionário atualizado com sucesso!!");
                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                //apos alterar desabilita os campos e botões
                btnSalvar.setEnabled(false);
                txtCargoFunc.setEnabled(false);
                txtSenhaFunc.setEnabled(false);
                txtSenhaConfFunc.setEnabled(false);
                btnExcluir.setEnabled(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao atualizar funcionário.");
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
       int selectedOption = JOptionPane.showConfirmDialog(null, "Deseja excluir Funcionario?", "Sistema informa:", JOptionPane.YES_NO_OPTION);
                    if (selectedOption == JOptionPane.YES_OPTION) {
                        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                        FuncionarioDAO funcDAO = new FuncionarioDAO();
                        funcDAO.delete(func);
                        JOptionPane.showMessageDialog(null, "Funcionario excluido com sucesso!!!");
                        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                        this.dispose();
                        
                    }
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbl_confirmeSenhaFunc;
    private javax.swing.JLabel lbl_emailCon;
    private javax.swing.JLabel lbl_emailFunc;
    private javax.swing.JLabel lbl_nomeFunc;
    private javax.swing.JLabel lbl_reFunc;
    private javax.swing.JLabel lbl_senhaFunc;
    private javax.swing.JTextField txtCargoFunc;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNomefunc;
    private javax.swing.JFormattedTextField txtReFunc;
    private javax.swing.JPasswordField txtSenhaConfFunc;
    private javax.swing.JPasswordField txtSenhaFunc;
    // End of variables declaration//GEN-END:variables
}
