/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.metalurgicametodo.swing;

import com.br.metalurgicametodo.dao.IDaoBase;
import com.br.metalurgicametodo.dao.PessoaDao;
import com.br.metalurgicametodo.dao.PessoaFisicaDAO;
import com.br.metalurgicametodo.dao.PessoaJuridicaDAO;
import com.br.metalurgicametodo.dao.TelefoneDAO;
import com.br.metalurgicametodo.entidades.Pessoa;
import com.br.metalurgicametodo.entidades.PessoaFisica;
import com.br.metalurgicametodo.entidades.PessoaJuridica;
import com.br.metalurgicametodo.entidades.Telefone;
import java.awt.Cursor;
import java.awt.Dimension;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author rds_d
 */
public class Tela_Cadastro extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tela_Cadastro
     */
    public Tela_Cadastro() {
        initComponents();
        Limitar();
        btm_feminino.setSelected(true);

    }

// metodo para habilitar ele
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }


public void Limitar() {
        //limitando os caracter que os campo de texto podem ter
        txtnumeroCasa.setDocument(new LimitarCaracter(txtnumeroCasa, 5));
        txtNumeroEmp.setDocument(new LimitarCaracter(txtNumeroEmp, 5));
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnGroupSexo = new javax.swing.ButtonGroup();
        painel_cadastro = new javax.swing.JTabbedPane();
        painel_pessoFisica = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lbl_nome = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        lbl_cpf = new javax.swing.JLabel();
        txt_cpf = new javax.swing.JFormattedTextField();
        lbl_rg = new javax.swing.JLabel();
        txt_rg = new javax.swing.JFormattedTextField();
        lbl_estadoCivil = new javax.swing.JLabel();
        cb_estadoCivil = new javax.swing.JComboBox();
        lbl_dataNascimento = new javax.swing.JLabel();
        lbl_sexo = new javax.swing.JLabel();
        btm_feminino = new javax.swing.JRadioButton();
        btm_masculino = new javax.swing.JRadioButton();
        lbl_telefone = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jftCelular = new javax.swing.JFormattedTextField();
        jftTelefone = new javax.swing.JFormattedTextField();
        jftDataNascimento = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        lbll_rua = new javax.swing.JLabel();
        lbl_numero = new javax.swing.JLabel();
        lbl_bairro = new javax.swing.JLabel();
        txt_bairro = new javax.swing.JTextField();
        lbl_cidade = new javax.swing.JLabel();
        txt_cidade = new javax.swing.JTextField();
        lbl_uf = new javax.swing.JLabel();
        cb_uf = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jftCEP = new javax.swing.JFormattedTextField();
        txtnumeroCasa = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        txt_rua = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lbl_nomeFantasia = new javax.swing.JLabel();
        lbl_representante = new javax.swing.JLabel();
        lbl_cnpj = new javax.swing.JLabel();
        txt_representante = new javax.swing.JTextField();
        txt_emailPJ = new javax.swing.JTextField();
        lbl_emailPJ = new javax.swing.JLabel();
        jftCNPJ = new javax.swing.JFormattedTextField();
        txt_nomeFantasia = new javax.swing.JTextField();
        lbl_razaoSocial = new javax.swing.JLabel();
        txt_razaoSocial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jftTelEmp = new javax.swing.JFormattedTextField();
        jftCelEmp = new javax.swing.JFormattedTextField();
        btnLimpar2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbll_rua1 = new javax.swing.JLabel();
        txt_rua1 = new javax.swing.JTextField();
        lbl_numero1 = new javax.swing.JLabel();
        lbl_bairro1 = new javax.swing.JLabel();
        txt_bairro1 = new javax.swing.JTextField();
        lbl_cidade1 = new javax.swing.JLabel();
        txt_cidade1 = new javax.swing.JTextField();
        lbl_uf1 = new javax.swing.JLabel();
        cb_uf1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jftCEPEmp = new javax.swing.JFormattedTextField();
        txtNumeroEmp = new javax.swing.JTextField();
        btnSalvarEmp = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro");

        painel_pessoFisica.setPreferredSize(new java.awt.Dimension(700, 650));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoa Fisica"));

        lbl_nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_nome.setText("Nome");

        txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeActionPerformed(evt);
            }
        });

        lbl_cpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_cpf.setText("CPF:");

        MaskFormatter mascaraCpf = null;
        try {
            txt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascaraCpf = new MaskFormatter("###.###.###-##")));
            mascaraCpf.setPlaceholderCharacter('_');
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbl_rg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_rg.setText("RG:");

        MaskFormatter mascaraRg = null;
        try {
            txt_rg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaraRg = new MaskFormatter("##.###.###-A")));
            mascaraRg.setPlaceholderCharacter('_');
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_rg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rgActionPerformed(evt);
            }
        });

        lbl_estadoCivil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_estadoCivil.setText("Estado Civil:");

        cb_estadoCivil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_estadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecionar", "Solteiro", "Casado" }));

        lbl_dataNascimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_dataNascimento.setText("Data de Nascimento:");

        lbl_sexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_sexo.setText("Sexo:");

        btnGroupSexo.add(btm_feminino);
        btm_feminino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btm_feminino.setText("Feminino");
        btm_feminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_femininoActionPerformed(evt);
            }
        });

        btnGroupSexo.add(btm_masculino);
        btm_masculino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btm_masculino.setText("Masculino");
        btm_masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_masculinoActionPerformed(evt);
            }
        });

        lbl_telefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_telefone.setText("Telefone:");

        lbl_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_email.setText("E-mail:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Celular: ");

        MaskFormatter mascaraCel = null;
        try {
            jftCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaraCel = new MaskFormatter("(##)#####-####")));
            mascaraCel.setPlaceholderCharacter('_');
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        MaskFormatter mascaraTel = null;
        try {
            jftTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaraTel = new MaskFormatter("(##)####-####")));
            mascaraTel.setPlaceholderCharacter('_');
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        MaskFormatter mascaraData = null;
        try {
            jftDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaraData = new MaskFormatter("##/##/####")));
            mascaraData.setPlaceholderCharacter('_');
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_estadoCivil)
                            .addComponent(lbl_cpf)
                            .addComponent(lbl_nome)
                            .addComponent(lbl_sexo)
                            .addComponent(lbl_email))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_estadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_telefone, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_dataNascimento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_rg, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jftCelular, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jftTelefone, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jftDataNascimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_rg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nome)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(btm_feminino)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btm_masculino))
                                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_cpf)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_rg)
                        .addComponent(txt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_estadoCivil)
                    .addComponent(cb_estadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_dataNascimento)
                    .addComponent(jftDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_sexo)
                    .addComponent(btm_feminino)
                    .addComponent(btm_masculino)
                    .addComponent(lbl_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jftCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_email))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Endereço")));

        lbll_rua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbll_rua.setText("Rua:");

        lbl_numero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_numero.setText("Nº:");

        lbl_bairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_bairro.setText("Bairro:");

        lbl_cidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_cidade.setText("Cidade:");

        lbl_uf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_uf.setText("UF:");

        cb_uf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_uf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecionar", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("CEP:");

        MaskFormatter mascaraCep = null;
        try {
            jftCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaraCep = new MaskFormatter("#####-###")));
            mascaraCep.setPlaceholderCharacter('_');
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtnumeroCasa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumeroCasaKeyTyped(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbll_rua)
                    .addComponent(lbl_bairro)
                    .addComponent(lbl_cidade)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jftCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_uf)
                        .addGap(18, 18, 18)
                        .addComponent(cb_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_bairro)
                            .addComponent(txt_rua))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_numero)
                        .addGap(18, 18, 18)
                        .addComponent(txtnumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbll_rua)
                    .addComponent(lbl_numero)
                    .addComponent(txtnumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_bairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cidade)
                    .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_uf)
                    .addComponent(cb_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jftCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnSalvar)))
        );

        javax.swing.GroupLayout painel_pessoFisicaLayout = new javax.swing.GroupLayout(painel_pessoFisica);
        painel_pessoFisica.setLayout(painel_pessoFisicaLayout);
        painel_pessoFisicaLayout.setHorizontalGroup(
            painel_pessoFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_pessoFisicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_pessoFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(69, 69, 69))
        );
        painel_pessoFisicaLayout.setVerticalGroup(
            painel_pessoFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_pessoFisicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        painel_cadastro.addTab("Pessoa Fisica", painel_pessoFisica);

        jPanel2.setPreferredSize(new java.awt.Dimension(637, 490));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Empresa"));

        lbl_nomeFantasia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_nomeFantasia.setText("Nome Fantasia");

        lbl_representante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_representante.setText("Representante:");

        lbl_cnpj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_cnpj.setText("CNPJ:");

        lbl_emailPJ.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_emailPJ.setText("E-mail:");

        MaskFormatter mascaraCnpj = null;
        try {
            jftCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascaraCnpj = new MaskFormatter("##.###.###/####-##")));
            mascaraCnpj.setPlaceholderCharacter('_');
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbl_razaoSocial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_razaoSocial.setText("Razão Socical:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Telefone:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Celular:");

        try{
            jftTelEmp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaraTel = new MaskFormatter("(##)####-####")));
            mascaraTel.setPlaceholderCharacter('_');
        }catch(java.text.ParseException ex)
        {
            ex.printStackTrace();
        }

        try{
            jftCelEmp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaraCel = new MaskFormatter("(##)#####-####")));
            mascaraCel.setPlaceholderCharacter('_');
        }catch(java.text.ParseException ex)
        {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nomeFantasia)
                            .addComponent(lbl_cnpj))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(txt_nomeFantasia, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jftCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbl_razaoSocial)
                        .addGap(18, 18, 18)
                        .addComponent(txt_razaoSocial))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_representante)
                            .addComponent(lbl_emailPJ)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_representante, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                            .addComponent(txt_emailPJ)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jftTelEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jftCelEmp)))))
                .addGap(31, 31, 31))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_razaoSocial)
                    .addComponent(txt_razaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nomeFantasia)
                    .addComponent(txt_nomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cnpj)
                    .addComponent(jftCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_representante)
                    .addComponent(txt_representante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_emailPJ)
                    .addComponent(txt_emailPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jftTelEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftCelEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLimpar2.setText("Limpar");
        btnLimpar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar2ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Endereço")));

        lbll_rua1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbll_rua1.setText("Rua:");

        lbl_numero1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_numero1.setText("Nº:");

        lbl_bairro1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_bairro1.setText("Bairro:");

        lbl_cidade1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_cidade1.setText("Cidade:");

        lbl_uf1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_uf1.setText("UF:");

        cb_uf1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_uf1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecionar", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("CEP: ");

        try {
            jftCEPEmp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaraCep = new MaskFormatter("#####-###")));
            mascaraCep.setPlaceholderCharacter('_');
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtNumeroEmp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroEmpKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbll_rua1)
                    .addComponent(lbl_bairro1)
                    .addComponent(lbl_cidade1)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txt_rua1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_numero1)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumeroEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_bairro1)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(txt_cidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lbl_uf1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cb_uf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(115, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jftCEPEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbll_rua1)
                    .addComponent(txt_rua1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_numero1)
                    .addComponent(txtNumeroEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_bairro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_bairro1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cidade1)
                    .addComponent(txt_cidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_uf1)
                    .addComponent(cb_uf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jftCEPEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnSalvarEmp.setText("Salvar");
        btnSalvarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLimpar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalvarEmp))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar2)
                    .addComponent(btnSalvarEmp))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        painel_cadastro.addTab("Pessoa Juridica", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        setBounds(185, 40, 686, 649);
    }// </editor-fold>//GEN-END:initComponents
    public String tipoSexo = "F";
    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeActionPerformed

    private void btm_femininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_femininoActionPerformed
        // pegar F ao clicar no botão de radio de sexo
        tipoSexo = btm_feminino.getText().substring(0, 1);

    }//GEN-LAST:event_btm_femininoActionPerformed

    private void txt_rgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rgActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            java.sql.Date data = null;
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            //verifica se o campo data de nascimento esta vazio
            if (jftDataNascimento.getText().substring(0, 1).equals(" ") || jftDataNascimento.getText().substring(0, 1).equals("_")) {

            } else {
                // pega data de nascimento do campo txt e aloca em uma variavel
                String dataStr = jftDataNascimento.getText();
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");

                try {
                    // converte a data de nascimento para o padrão do banco de dados
                    data = new java.sql.Date(format.parse(dataStr).getTime());

                

} catch (ParseException ex) {
                    Logger.getLogger(Tela_Cadastro.class  

.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            String painel = (String) painel_cadastro.getTitleAt(0);
            String tipoPessoa = String.valueOf(painel.charAt(0)) + String.valueOf(painel.charAt(7));
            Pessoa pessoa = new Pessoa();
            pessoa.setNome(txt_nome.getText());
            pessoa.setCep(jftCEP.getText());
            pessoa.setBairro(txt_bairro.getText());
            pessoa.setCidade(txt_cidade.getText());
            pessoa.setEmail(txt_email.getText());

            pessoa.setNumero(Integer.parseInt(txtnumeroCasa.getText()));
            pessoa.setTipoPessoa(tipoPessoa);
            pessoa.setUf((String) cb_uf.getSelectedItem());
            pessoa.setRua(txt_rua.getText());

            PessoaDao pessoaDAO = new PessoaDao();
            //pega informaçoes de Pessoa e salva no banco
            pessoaDAO.save(pessoa);
            Pessoa p2 = new Pessoa();
            //busca a ultima pessoa inserida
            p2 = pessoaDAO.buscarUltimaP();
            PessoaFisica pessoaF = new PessoaFisica();
            
            pessoaF.setPessoa(p2);
            pessoaF.setDataNascimento(data);
            pessoaF.setCpf(txt_cpf.getText());
            pessoaF.setRg(txt_rg.getText());
            pessoaF.setSexo(tipoSexo);

            pessoaF.setEstadoCivil(String.valueOf(cb_estadoCivil.getSelectedItem()));
            IDaoBase pessoaFDAO = new PessoaFisicaDAO();
            // salva uma pessoa fisica
            pessoaFDAO.save(pessoaF);
            Telefone telefone = new Telefone();
            telefone.setPessoa(p2);
            telefone.setTelefoneCelular(jftCelular.getText());
            telefone.setTelefoneFixo(jftTelefone.getText());
            IDaoBase telefoneDAO = new TelefoneDAO();
            // salva o telefone da pessoa
            telefoneDAO.save(telefone);
            
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            //exibe mensagem de cadastro realizado com sucesso
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao inserir Cliente");
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLimpar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar2ActionPerformed
        txt_razaoSocial.setText("");
        txt_nomeFantasia.setText("");
        txt_representante.setText("");
        jftCNPJ.setText("");
        txt_representante.setText("");
        txt_emailPJ.setText("");
        jftCelEmp.setText("");
        jftTelEmp.setText("");
        txt_rua1.setText("");
        txt_cidade1.setText("");
        txt_bairro1.setText("");
        txtNumeroEmp.setText("");
        jftCEPEmp.setText("");
        cb_uf1.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpar2ActionPerformed

    private void btnSalvarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEmpActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            String painel = (String) painel_cadastro.getTitleAt(1);
            String tipoPessoa = String.valueOf(painel.charAt(0)) + String.valueOf(painel.charAt(7));

            Pessoa pessoa = new Pessoa();
            pessoa.setNome(txt_representante.getText());
            pessoa.setBairro(txt_bairro1.getText());
            pessoa.setCep(jftCEPEmp.getText());
            pessoa.setCidade(txt_cidade1.getText());
            pessoa.setNumero(Integer.parseInt(txtNumeroEmp.getText()));
            pessoa.setRua(txt_rua1.getText());
            pessoa.setEmail(txt_emailPJ.getText());
            pessoa.setTipoPessoa(tipoPessoa);
            pessoa.setUf(String.valueOf(cb_uf1.getSelectedItem()));
            PessoaDao pessoaDAO = new PessoaDao();
            pessoaDAO.save(pessoa);

            Pessoa p2 = new Pessoa();
            p2 = pessoaDAO.buscarUltimaP();

            PessoaJuridica pessoaJ = new PessoaJuridica();
            pessoaJ.setCnpj(jftCNPJ.getText());
            pessoaJ.setNomeFantasia(txt_nomeFantasia.getText());
            pessoaJ.setPessoa(p2);
            pessoaJ.setRazaoSocial(txt_razaoSocial.getText());
            PessoaJuridicaDAO pJ = new PessoaJuridicaDAO();
            pJ.save(pessoaJ);

            Telefone telefone = new Telefone();
            telefone.setTelefoneFixo(jftTelEmp.getText());
            telefone.setTelefoneCelular(jftCelEmp.getText());
            telefone.setPessoa(p2);
            TelefoneDAO telefoneDAO = new TelefoneDAO();
            telefoneDAO.save(telefone);
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao inserir cliente");
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_btnSalvarEmpActionPerformed

    private void txtNumeroEmpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroEmpKeyTyped
        // restringe o campo de Numero de Empresa a so entrar caracteres do tipo numerico
        String caracteres = "0987654321";

        if (!caracteres.contains(evt.getKeyChar() + "")) {

            evt.consume();

        }


    }//GEN-LAST:event_txtNumeroEmpKeyTyped

    private void txtnumeroCasaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumeroCasaKeyTyped
             // restringe o campo de Numero de casa a so entrar caracteres do tipo numerico
        String caracteres = "0987654321";

        if (!caracteres.contains(evt.getKeyChar() + "")) {

            evt.consume();

        }


    }//GEN-LAST:event_txtnumeroCasaKeyTyped

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txt_nome.setText("");
        txt_cpf.setText("");
        txt_rg.setText("");
        cb_estadoCivil.setSelectedIndex(0);
        jftDataNascimento.setText("");
        btm_feminino.setSelected(true);
        btm_masculino.setSelected(false);
        jftCelular.setText("");
        jftTelefone.setText("");
        txt_email.setText("");
        txt_rua.setText("");
        txt_cidade.setText("");
        txt_bairro.setText("");
        jftCEP.setText("");
        txtnumeroCasa.setText("");
        cb_uf.setSelectedIndex(0);

    }//GEN-LAST:event_btnLimparActionPerformed

    private void btm_masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_masculinoActionPerformed
        tipoSexo = btm_masculino.getText().substring(0, 1);
    }//GEN-LAST:event_btm_masculinoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btm_feminino;
    private javax.swing.JRadioButton btm_masculino;
    private javax.swing.ButtonGroup btnGroupSexo;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLimpar2;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvarEmp;
    private javax.swing.JComboBox cb_estadoCivil;
    private javax.swing.JComboBox cb_uf;
    private javax.swing.JComboBox cb_uf1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JFormattedTextField jftCEP;
    private javax.swing.JFormattedTextField jftCEPEmp;
    private javax.swing.JFormattedTextField jftCNPJ;
    private javax.swing.JFormattedTextField jftCelEmp;
    private javax.swing.JFormattedTextField jftCelular;
    private javax.swing.JFormattedTextField jftDataNascimento;
    private javax.swing.JFormattedTextField jftTelEmp;
    private javax.swing.JFormattedTextField jftTelefone;
    private javax.swing.JLabel lbl_bairro;
    private javax.swing.JLabel lbl_bairro1;
    private javax.swing.JLabel lbl_cidade;
    private javax.swing.JLabel lbl_cidade1;
    private javax.swing.JLabel lbl_cnpj;
    private javax.swing.JLabel lbl_cpf;
    private javax.swing.JLabel lbl_dataNascimento;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_emailPJ;
    private javax.swing.JLabel lbl_estadoCivil;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_nomeFantasia;
    private javax.swing.JLabel lbl_numero;
    private javax.swing.JLabel lbl_numero1;
    private javax.swing.JLabel lbl_razaoSocial;
    private javax.swing.JLabel lbl_representante;
    private javax.swing.JLabel lbl_rg;
    private javax.swing.JLabel lbl_sexo;
    private javax.swing.JLabel lbl_telefone;
    private javax.swing.JLabel lbl_uf;
    private javax.swing.JLabel lbl_uf1;
    private javax.swing.JLabel lbll_rua;
    private javax.swing.JLabel lbll_rua1;
    private javax.swing.JTabbedPane painel_cadastro;
    private javax.swing.JPanel painel_pessoFisica;
    private javax.swing.JTextField txtNumeroEmp;
    private javax.swing.JTextField txt_bairro;
    private javax.swing.JTextField txt_bairro1;
    private javax.swing.JTextField txt_cidade;
    private javax.swing.JTextField txt_cidade1;
    private javax.swing.JFormattedTextField txt_cpf;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_emailPJ;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_nomeFantasia;
    private javax.swing.JTextField txt_razaoSocial;
    private javax.swing.JTextField txt_representante;
    private javax.swing.JFormattedTextField txt_rg;
    private javax.swing.JTextField txt_rua;
    private javax.swing.JTextField txt_rua1;
    private javax.swing.JTextField txtnumeroCasa;
    // End of variables declaration//GEN-END:variables
}
