/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.metalurgicametodo.swing;

import com.br.metalurgicametodo.relatorio.Relatorio;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rds_d
 */
public class Tela_Relatorio extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tela_Relatorio
     */
    public Tela_Relatorio() {
        initComponents();
    }
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_GeraRelatorio = new javax.swing.JPanel();
        lbl_relatorio = new javax.swing.JLabel();
        cb_TipoRelatorio = new javax.swing.JComboBox();
        lbl_tipoGrafico = new javax.swing.JLabel();
        cb_tipoGrafico = new javax.swing.JComboBox();
        btm_gerarRelatorio = new javax.swing.JButton();
        btm_gerarGrafico = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Relatorio");

        pn_GeraRelatorio.setBackground(new java.awt.Color(204, 204, 204));

        lbl_relatorio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_relatorio.setText("Tipo de Relátorio:");

        cb_TipoRelatorio.setBackground(new java.awt.Color(204, 204, 204));
        cb_TipoRelatorio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_TipoRelatorio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecionar", "Clientes", "Produtos", "Vendas" }));
        cb_TipoRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_TipoRelatorioActionPerformed(evt);
            }
        });

        lbl_tipoGrafico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_tipoGrafico.setText("Tipo de grafíco:");

        cb_tipoGrafico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_tipoGrafico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecionar", "Coluna", "Pizza" }));

        btm_gerarRelatorio.setBackground(new java.awt.Color(255, 255, 255));
        btm_gerarRelatorio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btm_gerarRelatorio.setText("Gerar Relátorio");
        btm_gerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_gerarRelatorioActionPerformed(evt);
            }
        });

        btm_gerarGrafico.setBackground(new java.awt.Color(255, 255, 255));
        btm_gerarGrafico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btm_gerarGrafico.setText("Gerar Gráfico");
        btm_gerarGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_gerarGraficoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_GeraRelatorioLayout = new javax.swing.GroupLayout(pn_GeraRelatorio);
        pn_GeraRelatorio.setLayout(pn_GeraRelatorioLayout);
        pn_GeraRelatorioLayout.setHorizontalGroup(
            pn_GeraRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_GeraRelatorioLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(pn_GeraRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_relatorio)
                    .addComponent(lbl_tipoGrafico)
                    .addComponent(btm_gerarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_GeraRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_TipoRelatorio, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_tipoGrafico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btm_gerarGrafico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        pn_GeraRelatorioLayout.setVerticalGroup(
            pn_GeraRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_GeraRelatorioLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pn_GeraRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cb_TipoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_relatorio))
                .addGap(18, 18, 18)
                .addGroup(pn_GeraRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cb_tipoGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tipoGrafico))
                .addGap(18, 18, 18)
                .addGroup(pn_GeraRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btm_gerarGrafico)
                    .addComponent(btm_gerarRelatorio))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_GeraRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_GeraRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(200, 25, 452, 244);
    }// </editor-fold>//GEN-END:initComponents

    private void btm_gerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_gerarRelatorioActionPerformed
        // TODO add your handling code here:

        Relatorio r = new Relatorio();

        try {
            if (cb_TipoRelatorio.getSelectedItem().toString().equalsIgnoreCase("Selecionar")) {
                JOptionPane.showMessageDialog(null, "Selecione uma opção");
            }

            if (cb_TipoRelatorio.getSelectedItem().toString().equalsIgnoreCase("Clientes")) {
                r.gerarRelatorioClientes();
            }
            if (cb_TipoRelatorio.getSelectedItem().toString().equalsIgnoreCase("Produtos")) {
                r.gerarRelatorioProdutos();
            }
            if (cb_TipoRelatorio.getSelectedItem().toString().equalsIgnoreCase("Vendas")) {
                r.gerarRelatorioVendas();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Relatorio.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btm_gerarRelatorioActionPerformed

    private void cb_TipoRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_TipoRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_TipoRelatorioActionPerformed

    private void btm_gerarGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_gerarGraficoActionPerformed
        Relatorio r = new Relatorio();
        try{
        if (cb_tipoGrafico.getSelectedItem().toString().equalsIgnoreCase("Selecionar")) {
            JOptionPane.showMessageDialog(null, "Selecione uma opção");
        }

        if (cb_tipoGrafico.getSelectedItem().toString().equalsIgnoreCase("Coluna")) {
            r.gerarGraficoBarra();
        }
        if (cb_tipoGrafico.getSelectedItem().toString().equalsIgnoreCase("Pizza")) {
            r.gerarGraficoPizza();
        }
        }catch(SQLException ex){
            Logger.getLogger(Tela_Relatorio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btm_gerarGraficoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm_gerarGrafico;
    private javax.swing.JButton btm_gerarRelatorio;
    private javax.swing.JComboBox cb_TipoRelatorio;
    private javax.swing.JComboBox cb_tipoGrafico;
    private javax.swing.JLabel lbl_relatorio;
    private javax.swing.JLabel lbl_tipoGrafico;
    private javax.swing.JPanel pn_GeraRelatorio;
    // End of variables declaration//GEN-END:variables
}
