/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.metalurgicametodo.swing;

import com.br.metalurgicametodo.dao.FuncionarioDAO;
import com.br.metalurgicametodo.entidades.Funcionario;
import de.javasoft.plaf.synthetica.SyntheticaSilverMoonLookAndFeel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import static javax.swing.UIManager.setLookAndFeel;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author rds_d
 */
public class Tela_Login extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Login
     */
    public Tela_Login() throws ParseException {
        try {
            //com.seaglasslookandfeel.SeaGlassLookAndFeel
            UIManager.setLookAndFeel(new SyntheticaSilverMoonLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Tela_Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        setTitle("Tela Inicial");
        getRootPane().setDefaultButton(btm_Logar);
        Toolkit kit = Toolkit.getDefaultToolkit();
        Dimension tamanhoTela = kit.getScreenSize();
        SwingUtilities.updateComponentTreeUI(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txt_Login = new javax.swing.JTextField();
        lbl_Senha = new javax.swing.JLabel();
        txt_Senha = new javax.swing.JPasswordField();
        lblTitulo = new javax.swing.JLabel();
        btm_Logar = new javax.swing.JButton();
        lbl_EsqueceuSenha = new javax.swing.JLabel();
        lbl_Login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 110, 80, 20);
        getContentPane().add(txt_Login);
        txt_Login.setBounds(210, 100, 240, 30);

        lbl_Senha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_Senha.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Senha.setText("Senha:");
        getContentPane().add(lbl_Senha);
        lbl_Senha.setBounds(110, 160, 80, 22);

        txt_Senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_SenhaKeyPressed(evt);
            }
        });
        getContentPane().add(txt_Senha);
        txt_Senha.setBounds(210, 150, 240, 30);

        lblTitulo.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("BEM VINDO");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(180, 30, 260, 40);

        btm_Logar.setBackground(new java.awt.Color(255, 255, 255));
        btm_Logar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btm_Logar.setText("Entrar");
        btm_Logar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_LogarActionPerformed(evt);
            }
        });
        getContentPane().add(btm_Logar);
        btm_Logar.setBounds(370, 220, 80, 30);

        lbl_EsqueceuSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_EsqueceuSenha.setForeground(new java.awt.Color(255, 255, 255));
        lbl_EsqueceuSenha.setText("Esqueceu a senha?");
        getContentPane().add(lbl_EsqueceuSenha);
        lbl_EsqueceuSenha.setBounds(210, 190, 140, 17);

        lbl_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/metalurgicametodo/img/fundo_login.jpg"))); // NOI18N
        lbl_Login.setMaximumSize(new java.awt.Dimension(600, 600));
        lbl_Login.setMinimumSize(new java.awt.Dimension(600, 600));
        lbl_Login.setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().add(lbl_Login);
        lbl_Login.setBounds(0, 0, 600, 360);

        setBounds(0, 0, 595, 379);
    }// </editor-fold>//GEN-END:initComponents

    public void keyPressed(KeyEvent e) {
    //aciona o botão entrar ao apertar o enter

        if (e.getKeyCode() == KeyEvent.VK_ENTER) {

            // faz qualquer coisa que você quiser    
            btm_Logar.doClick();
            //jButton1ActionPerformed(evt); // Não funciona pois este é um ActionEvent dentro de um KeyEvent  
        }
  //  return;  
    }
    private void btm_LogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_LogarActionPerformed

        try {

            String login = txt_Login.getText();
            String senha = String.valueOf(txt_Senha.getPassword());

            FuncionarioDAO funcDAO = new FuncionarioDAO();
            Funcionario func = new Funcionario();
            func = funcDAO.buscarLogin(login);

            if (func != null) {

                if (senha.equals(func.getSenha()) && login.equals(func.getLogin())) {
                    Tela_Principal tp = new Tela_Principal();
                    tp.setExtendedState(MAXIMIZED_BOTH);
                    tp.setVisible(true);
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(null, "Login ou senha incoretos!", "ERRO!", JOptionPane.ERROR_MESSAGE);

                }
            } else {
                JOptionPane.showMessageDialog(null, "Login não encontrado!", "ERRO!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao logar");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btm_LogarActionPerformed

    private void txt_SenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SenhaKeyPressed

    }//GEN-LAST:event_txt_SenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Tela_Login tl = null;
                try {
                    tl = new Tela_Login();
                } catch (ParseException ex) {
                    Logger.getLogger(Tela_Login.class.getName()).log(Level.SEVERE, null, ex);
                }
                tl.setLocationRelativeTo(null);

                tl.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm_Logar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lbl_EsqueceuSenha;
    private javax.swing.JLabel lbl_Login;
    private javax.swing.JLabel lbl_Senha;
    private javax.swing.JTextField txt_Login;
    private javax.swing.JPasswordField txt_Senha;
    // End of variables declaration//GEN-END:variables
}
