/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.metalurgicametodo.swing;

import com.br.metalurgicametodo.dao.PessoaDao;
import com.br.metalurgicametodo.dao.PessoaFisicaDAO;
import com.br.metalurgicametodo.dao.TelefoneDAO;
import com.br.metalurgicametodo.entidades.Pessoa;
import com.br.metalurgicametodo.entidades.PessoaFisica;
import com.br.metalurgicametodo.entidades.Telefone;
import java.awt.Cursor;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Bruno
 */
//Classe que serve para editar e visualizar pessoa fisica
public class VisualizarPessoaFisica extends javax.swing.JInternalFrame {

    /**
     * Creates new form VisualizarPessoaFisica
     */
    public static PessoaFisica pessoaFisica = null;
    public static Pessoa pessoa = null;
    public static Telefone telefone = null;
    public static String tipoSexo = null;

    public VisualizarPessoaFisica() {
        initComponents();
        Limitar();
        try{
        // pega informaçoes da pessoa fisica da classe Swing buscarCliente e insere ela no campo de texto
        pessoaFisica = new PessoaFisica();
        PessoaFisicaDAO pfDAO = new PessoaFisicaDAO();
        pessoaFisica = BuscarCliente.pF;
        txt_bairro.setText(pessoaFisica.getPessoa().getBairro());
        txt_cidade.setText(pessoaFisica.getPessoa().getCidade());
        txt_cpf.setText(pessoaFisica.getCpf());
        txt_email.setText(pessoaFisica.getPessoa().getEmail());
        txt_nome.setText(pessoaFisica.getPessoa().getNome());
        txt_rg.setText(pessoaFisica.getRg());
        txt_rua.setText(pessoaFisica.getPessoa().getRua());
        txtnumeroCasa.setText(String.valueOf(pessoaFisica.getPessoa().getNumero()));
        jftCEP.setText(pessoaFisica.getPessoa().getCep());
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        Date d1 = (Date) (pessoaFisica.getDataNascimento());
        String data = format.format(d1);
        jftDataNascimento.setText(data);
        TelefoneDAO teleDAO = new TelefoneDAO();
        telefone = new Telefone();
        telefone = teleDAO.buscarPorCodigoP(pessoaFisica.getPessoa().getCodigoPessoa());
        jftCelular.setText(telefone.getTelefoneCelular());
        jftTelefone.setText(telefone.getTelefoneFixo());
        if (pessoaFisica.getSexo().equalsIgnoreCase("M")) {
            btm_masculino.setSelected(true);
        } else {
            btm_feminino.setSelected(true);
        }
        cb_uf.setSelectedItem(pessoaFisica.getPessoa().getUf());
        cb_estadoCivil.setSelectedItem(pessoaFisica.getEstadoCivil());
        pessoa = pessoaFisica.getPessoa();
        tipoSexo = pessoaFisica.getSexo();
    }catch(Exception e)
    {
        JOptionPane.showMessageDialog(null, "Erro ao visualizar pessoa fisica");
    }
        }
    public void Limitar() {
        txtnumeroCasa.setDocument(new LimitarCaracter(txtnumeroCasa, 5));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_pessoFisica = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lbl_nome = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        lbl_cpf = new javax.swing.JLabel();
        txt_cpf = new javax.swing.JFormattedTextField();
        lbl_rg = new javax.swing.JLabel();
        txt_rg = new javax.swing.JFormattedTextField();
        lbl_estadoCivil = new javax.swing.JLabel();
        cb_estadoCivil = new javax.swing.JComboBox();
        lbl_dataNascimento = new javax.swing.JLabel();
        lbl_sexo = new javax.swing.JLabel();
        btm_feminino = new javax.swing.JRadioButton();
        btm_masculino = new javax.swing.JRadioButton();
        lbl_telefone = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jftCelular = new javax.swing.JFormattedTextField();
        jftTelefone = new javax.swing.JFormattedTextField();
        jftDataNascimento = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        lbll_rua = new javax.swing.JLabel();
        txt_rua = new javax.swing.JTextField();
        lbl_numero = new javax.swing.JLabel();
        lbl_bairro = new javax.swing.JLabel();
        txt_bairro = new javax.swing.JTextField();
        lbl_cidade = new javax.swing.JLabel();
        txt_cidade = new javax.swing.JTextField();
        lbl_uf = new javax.swing.JLabel();
        cb_uf = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jftCEP = new javax.swing.JFormattedTextField();
        txtnumeroCasa = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pessoa Fisica");
        setPreferredSize(new java.awt.Dimension(766, 580));

        painel_pessoFisica.setPreferredSize(new java.awt.Dimension(700, 650));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoa Fisica"));

        lbl_nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_nome.setText("Nome");

        txt_nome.setEnabled(false);

        lbl_cpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_cpf.setText("CPF:");

        MaskFormatter mascaraCpf = null;
        try {
            txt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaraCpf = new MaskFormatter("###.###.###-##")));
            mascaraCpf.setPlaceholderCharacter('_');
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cpf.setEnabled(false);

        lbl_rg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_rg.setText("RG:");

        MaskFormatter mascaraRg = null;
        try {
            txt_rg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaraRg = new MaskFormatter("##.###.###-#")));
            mascaraRg.setPlaceholderCharacter('_');
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_rg.setEnabled(false);
        txt_rg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rgActionPerformed(evt);
            }
        });

        lbl_estadoCivil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_estadoCivil.setText("Estado Civil:");

        cb_estadoCivil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_estadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecionar", "Solteiro", "Casado" }));
        cb_estadoCivil.setEnabled(false);

        lbl_dataNascimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_dataNascimento.setText("Data de Nascimento:");

        lbl_sexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_sexo.setText("Sexo:");

        btm_feminino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btm_feminino.setText("Feminino");
        btm_feminino.setEnabled(false);
        btm_feminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_femininoActionPerformed(evt);
            }
        });

        btm_masculino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btm_masculino.setText("Masculino");
        btm_masculino.setEnabled(false);
        btm_masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_masculinoActionPerformed(evt);
            }
        });

        lbl_telefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_telefone.setText("Telefone:");

        lbl_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_email.setText("E-mail:");

        txt_email.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Celular: ");

        MaskFormatter mascaracel = null;
        try {
            jftCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaracel = new MaskFormatter("(##)#####-####")));
            mascaracel.setPlaceholderCharacter('_');
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCelular.setEnabled(false);

        try {
            MaskFormatter mascaratel = null;
            jftTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaratel = new MaskFormatter("(##)####-####")));
            mascaratel.setPlaceholderCharacter('_');
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftTelefone.setEnabled(false);

        MaskFormatter mascaradata=null;
        try {
            jftDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaradata = new MaskFormatter("##/##/####")));
            mascaradata.setPlaceholderCharacter('_');
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDataNascimento.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_estadoCivil)
                    .addComponent(lbl_cpf)
                    .addComponent(lbl_nome)
                    .addComponent(lbl_sexo)
                    .addComponent(lbl_email))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_estadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_rg, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_dataNascimento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_telefone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jftTelefone)
                    .addComponent(jftCelular)
                    .addComponent(txt_rg)
                    .addComponent(jftDataNascimento))
                .addGap(17, 17, 17))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btm_feminino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btm_masculino))
                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_cpf)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_rg)
                        .addComponent(txt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_estadoCivil)
                    .addComponent(cb_estadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_dataNascimento)
                    .addComponent(jftDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_sexo)
                    .addComponent(btm_feminino)
                    .addComponent(btm_masculino)
                    .addComponent(lbl_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_email)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jftCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Endereço")));

        lbll_rua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbll_rua.setText("Rua:");

        txt_rua.setEnabled(false);

        lbl_numero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_numero.setText("Nº:");

        lbl_bairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_bairro.setText("Bairro:");

        txt_bairro.setEnabled(false);

        lbl_cidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_cidade.setText("Cidade:");

        txt_cidade.setEnabled(false);

        lbl_uf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_uf.setText("UF:");

        cb_uf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_uf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecionar", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cb_uf.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("CEP:");

        MaskFormatter mascaracep = null;
        try {
            jftCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaracep = new MaskFormatter("#####-###")));
            mascaracep.setPlaceholderCharacter('_');
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCEP.setEnabled(false);

        txtnumeroCasa.setEnabled(false);
        txtnumeroCasa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumeroCasaKeyTyped(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbll_rua)
                            .addComponent(lbl_bairro)
                            .addComponent(lbl_cidade)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jftCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEditar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_bairro, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl_uf)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cb_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_rua, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(23, 23, 23)
                                .addComponent(lbl_numero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtnumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbll_rua)
                    .addComponent(txt_rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_numero)
                    .addComponent(txtnumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_bairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cidade)
                    .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_uf)
                    .addComponent(cb_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jftCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnSalvar)))
        );

        javax.swing.GroupLayout painel_pessoFisicaLayout = new javax.swing.GroupLayout(painel_pessoFisica);
        painel_pessoFisica.setLayout(painel_pessoFisicaLayout);
        painel_pessoFisicaLayout.setHorizontalGroup(
            painel_pessoFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_pessoFisicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_pessoFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        painel_pessoFisicaLayout.setVerticalGroup(
            painel_pessoFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_pessoFisicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(painel_pessoFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painel_pessoFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(56, 56, 56)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_rgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rgActionPerformed

    private void btm_femininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_femininoActionPerformed
        tipoSexo = btm_feminino.getText();
    }//GEN-LAST:event_btm_femininoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
         setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
             //salva a nova alteração feita na pessoa Fisica
            pessoa.setBairro(txt_bairro.getText());
            pessoa.setCep(jftCEP.getText());
            pessoa.setCidade(txt_cidade.getText());
            pessoa.setEmail(txt_email.getText());
            pessoa.setNumero(Integer.parseInt(txtnumeroCasa.getText()));
            pessoa.setNome(txt_nome.getText());

            pessoa.setUf(String.valueOf(cb_uf.getSelectedItem()));
            pessoa.setRua(txt_rua.getText());
            PessoaDao pDAO = new PessoaDao();
            pDAO.update(pessoa);
            pessoaFisica.setPessoa(pessoa);
            pessoaFisica.setCpf(txt_cpf.getText());
            String dataStr = jftDataNascimento.getText();
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date data = null;
            try {
                data = new java.sql.Date(format.parse(dataStr).getTime());

            } catch (ParseException ex) {
                Logger.getLogger(Tela_Cadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
            pessoaFisica.setDataNascimento(data);
            pessoaFisica.setEstadoCivil(String.valueOf(cb_estadoCivil.getSelectedItem()));
            pessoaFisica.setRg(txt_rg.getText());
            pessoaFisica.setSexo(tipoSexo);
            PessoaFisicaDAO pfDAO = new PessoaFisicaDAO();
            pfDAO.update(pessoaFisica);
            telefone.setPessoa(pessoa);
            telefone.setTelefoneCelular(jftCelular.getText());
            telefone.setTelefoneFixo(jftTelefone.getText());
            TelefoneDAO telDAO = new TelefoneDAO();
            telDAO.update(telefone);
             setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            JOptionPane.showMessageDialog(null, "Alteração do cadastro realizado com sucesso");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao inserir cliente");
        }
        // apos salvar desabilita todos os campos de textos e o botão salvar
        btnSalvar.setEnabled(false);
        txt_nome.setEnabled(false);
        txt_email.setEnabled(false);
        txt_bairro.setEnabled(false);
        txt_cidade.setEnabled(false);
        txt_cpf.setEnabled(false);
        txt_rg.setEnabled(false);
        txtnumeroCasa.setEnabled(false);
        txt_rua.setEnabled(false);
        jftCEP.setEnabled(false);
        jftCelular.setEnabled(false);
        jftDataNascimento.setEnabled(false);
        jftTelefone.setEnabled(false);
        btm_feminino.setEnabled(false);
        btm_masculino.setEnabled(false);
        cb_estadoCivil.setEnabled(false);
        cb_uf.setEnabled(false);
        btnSalvar.setEnabled(false);
         setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // habilitado todos os campos que o usuario pode alterar
        txt_nome.setEnabled(true);
        txt_email.setEnabled(true);
        txt_bairro.setEnabled(true);
        txt_cidade.setEnabled(true);
        txt_cpf.setEnabled(true);
        txt_rg.setEnabled(true);
        txtnumeroCasa.setEnabled(true);
        txt_rua.setEnabled(true);
        jftCEP.setEnabled(true);
        jftCelular.setEnabled(true);
        jftDataNascimento.setEnabled(true);
        jftTelefone.setEnabled(true);
        btm_feminino.setEnabled(true);
        btm_masculino.setEnabled(true);
        cb_estadoCivil.setEnabled(true);
        cb_uf.setEnabled(true);
        btnSalvar.setEnabled(true);

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btm_masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_masculinoActionPerformed
        tipoSexo = btm_masculino.getText();
    }//GEN-LAST:event_btm_masculinoActionPerformed

    private void txtnumeroCasaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumeroCasaKeyTyped
        String caracteres = "0987654321";

        if (!caracteres.contains(evt.getKeyChar() + "")) {

            evt.consume();

        }
    }//GEN-LAST:event_txtnumeroCasaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btm_feminino;
    private javax.swing.JRadioButton btm_masculino;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cb_estadoCivil;
    private javax.swing.JComboBox cb_uf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JFormattedTextField jftCEP;
    private javax.swing.JFormattedTextField jftCelular;
    private javax.swing.JFormattedTextField jftDataNascimento;
    private javax.swing.JFormattedTextField jftTelefone;
    private javax.swing.JLabel lbl_bairro;
    private javax.swing.JLabel lbl_cidade;
    private javax.swing.JLabel lbl_cpf;
    private javax.swing.JLabel lbl_dataNascimento;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_estadoCivil;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_numero;
    private javax.swing.JLabel lbl_rg;
    private javax.swing.JLabel lbl_sexo;
    private javax.swing.JLabel lbl_telefone;
    private javax.swing.JLabel lbl_uf;
    private javax.swing.JLabel lbll_rua;
    private javax.swing.JPanel painel_pessoFisica;
    private javax.swing.JTextField txt_bairro;
    private javax.swing.JTextField txt_cidade;
    private javax.swing.JFormattedTextField txt_cpf;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JFormattedTextField txt_rg;
    private javax.swing.JTextField txt_rua;
    private javax.swing.JTextField txtnumeroCasa;
    // End of variables declaration//GEN-END:variables
}
