/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.metalurgicametodo.swing;

import com.br.metalurgicametodo.dao.PessoaDao;
import com.br.metalurgicametodo.dao.PessoaJuridicaDAO;
import com.br.metalurgicametodo.dao.TelefoneDAO;
import com.br.metalurgicametodo.entidades.Pessoa;
import com.br.metalurgicametodo.entidades.PessoaJuridica;
import com.br.metalurgicametodo.entidades.Telefone;
import java.awt.Cursor;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Bruno
 */
public class VisualizarPessoaJuridica extends javax.swing.JInternalFrame {

    /**
     * Creates new form VisualizarPessoaJuridica
     */
    public static PessoaJuridica pessoaJuridica = null;
    public static Telefone tel = null;
    public static Pessoa pessoa = null;
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public VisualizarPessoaJuridica() {
        initComponents();
        Limitar();
        try{
        // pessoa juridica recebe o objeto pj , e insere essas informações nos campos de texto
        pessoaJuridica = new PessoaJuridica();
        PessoaJuridicaDAO pjDAO = new PessoaJuridicaDAO();
        pessoaJuridica = BuscarCliente.pJ;
        txtNumeroEmp.setText(String.valueOf(pessoaJuridica.getPessoa().getNumero()));
        txt_bairro1.setText(pessoaJuridica.getPessoa().getBairro());
        txt_cidade1.setText(pessoaJuridica.getPessoa().getCidade());
        txt_emailPJ1.setText(pessoaJuridica.getPessoa().getEmail());
        txt_nomeFantasia1.setText(pessoaJuridica.getNomeFantasia());
        txt_razaoSocial1.setText(pessoaJuridica.getRazaoSocial());
        txt_representante1.setText(pessoaJuridica.getPessoa().getNome());
        txt_rua1.setText(pessoaJuridica.getPessoa().getRua());
        jftCEPEmp.setText(pessoaJuridica.getPessoa().getCep());
        jftCNPJ1.setText(pessoaJuridica.getCnpj());
        tel = new Telefone();
        TelefoneDAO telDAO = new TelefoneDAO();
        tel = telDAO.buscarPorCodigoP(pessoaJuridica.getPessoa().getCodigoPessoa());
        jftCelEmp1.setText(tel.getTelefoneCelular());
        jftTelEmp1.setText(tel.getTelefoneFixo());
        cb_uf1.setSelectedItem(pessoaJuridica.getPessoa().getUf());
        pessoa = pessoaJuridica.getPessoa();
        }catch(Exception e)
        {
           JOptionPane.showMessageDialog(null, "Erro ao visualizar Pessoa Juridica!!!");
        }
        }

    public void Limitar() {
        //limitar os caracter a serem inseridos
        txtNumeroEmp.setDocument(new LimitarCaracter(txtNumeroEmp, 5));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lbl_nomeFantasia1 = new javax.swing.JLabel();
        lbl_representante1 = new javax.swing.JLabel();
        lbl_cnpj1 = new javax.swing.JLabel();
        txt_representante1 = new javax.swing.JTextField();
        txt_emailPJ1 = new javax.swing.JTextField();
        lbl_emailPJ1 = new javax.swing.JLabel();
        jftCNPJ1 = new javax.swing.JFormattedTextField();
        txt_nomeFantasia1 = new javax.swing.JTextField();
        lbl_razaoSocial1 = new javax.swing.JLabel();
        txt_razaoSocial1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jftTelEmp1 = new javax.swing.JFormattedTextField();
        jftCelEmp1 = new javax.swing.JFormattedTextField();
        btnEditar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbll_rua1 = new javax.swing.JLabel();
        txt_rua1 = new javax.swing.JTextField();
        lbl_numero1 = new javax.swing.JLabel();
        lbl_bairro1 = new javax.swing.JLabel();
        txt_bairro1 = new javax.swing.JTextField();
        lbl_cidade1 = new javax.swing.JLabel();
        txt_cidade1 = new javax.swing.JTextField();
        lbl_uf1 = new javax.swing.JLabel();
        cb_uf1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jftCEPEmp = new javax.swing.JFormattedTextField();
        txtNumeroEmp = new javax.swing.JTextField();
        btnSalvarEmp = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pessoa Juridica");

        jPanel3.setPreferredSize(new java.awt.Dimension(637, 490));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Empresa"));

        lbl_nomeFantasia1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_nomeFantasia1.setText("Nome Fantasia");

        lbl_representante1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_representante1.setText("Representante:");

        lbl_cnpj1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_cnpj1.setText("CNPJ:");

        txt_representante1.setEnabled(false);

        txt_emailPJ1.setEnabled(false);

        lbl_emailPJ1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_emailPJ1.setText("E-mail:");

        MaskFormatter mascaraCnpj = null;

        try {
            jftCNPJ1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaraCnpj = new MaskFormatter("##.###.###/####-##")));
            mascaraCnpj.setPlaceholderCharacter('_');
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCNPJ1.setEnabled(false);

        txt_nomeFantasia1.setEnabled(false);

        lbl_razaoSocial1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_razaoSocial1.setText("Razão Socical:");

        txt_razaoSocial1.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Telefone:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Celular:");

        MaskFormatter mascaratel = null;
        try {
            jftTelEmp1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaratel = new MaskFormatter("(##)####-####")));
            mascaratel.setPlaceholderCharacter('_');
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftTelEmp1.setEnabled(false);

        MaskFormatter mascaracel = null;
        try {
            jftCelEmp1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaracel = new MaskFormatter("(##)#####-####")));
            mascaracel.setPlaceholderCharacter('_');
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCelEmp1.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nomeFantasia1)
                            .addComponent(lbl_cnpj1))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(txt_nomeFantasia1))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jftCNPJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lbl_razaoSocial1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_razaoSocial1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_representante1)
                            .addComponent(lbl_emailPJ1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_representante1)
                            .addComponent(txt_emailPJ1)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jftTelEmp1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jftCelEmp1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)))))
                .addGap(31, 31, 31))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_razaoSocial1)
                    .addComponent(txt_razaoSocial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nomeFantasia1)
                    .addComponent(txt_nomeFantasia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cnpj1)
                    .addComponent(jftCNPJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_representante1)
                    .addComponent(txt_representante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_emailPJ1)
                    .addComponent(txt_emailPJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jftTelEmp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftCelEmp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Endereço")));

        lbll_rua1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbll_rua1.setText("Rua:");

        txt_rua1.setEnabled(false);

        lbl_numero1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_numero1.setText("Nº:");

        lbl_bairro1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_bairro1.setText("Bairro:");

        txt_bairro1.setEnabled(false);

        lbl_cidade1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_cidade1.setText("Cidade:");

        txt_cidade1.setEnabled(false);

        lbl_uf1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_uf1.setText("UF:");

        cb_uf1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_uf1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecionar", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cb_uf1.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("CEP: ");

        MaskFormatter mascaracep = null;
        try {
            jftCEPEmp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaracep = new MaskFormatter("#####-###")));
            mascaracep.setPlaceholderCharacter('_');
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCEPEmp.setText("");
        jftCEPEmp.setEnabled(false);

        txtNumeroEmp.setEnabled(false);
        txtNumeroEmp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroEmpKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbll_rua1)
                    .addComponent(lbl_bairro1)
                    .addComponent(lbl_cidade1)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txt_rua1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_numero1)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumeroEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_bairro1)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(txt_cidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lbl_uf1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cb_uf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(115, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jftCEPEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbll_rua1)
                    .addComponent(txt_rua1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_numero1)
                    .addComponent(txtNumeroEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_bairro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_bairro1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cidade1)
                    .addComponent(txt_cidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_uf1)
                    .addComponent(cb_uf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jftCEPEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnSalvarEmp.setText("Salvar");
        btnSalvarEmp.setEnabled(false);
        btnSalvarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvarEmp))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnSalvarEmp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        txtNumeroEmp.setEnabled(true);
        txt_bairro1.setEnabled(true);
        txt_cidade1.setEnabled(true);
        txt_emailPJ1.setEnabled(true);
        txt_nomeFantasia1.setEnabled(true);
        txt_razaoSocial1.setEnabled(true);
        txt_representante1.setEnabled(true);
        txt_rua1.setEnabled(true);
        jftCEPEmp.setEnabled(true);
        jftCNPJ1.setEnabled(true);
        jftCelEmp1.setEnabled(true);
        jftTelEmp1.setEnabled(true);
        cb_uf1.setEnabled(true);
        btnSalvarEmp.setEnabled(true);

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSalvarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEmpActionPerformed
         setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            //pega as informaçoes do campo de texto e atribui aos seus respectivos objetos
            pessoa.setBairro(txt_bairro1.getText());
            pessoa.setCep(jftCEPEmp.getText());
            pessoa.setCidade(txt_cidade1.getText());
            pessoa.setEmail(txt_emailPJ1.getText());
            pessoa.setNome(txt_representante1.getText());
            pessoa.setNumero(Integer.parseInt(txtNumeroEmp.getText()));
            pessoa.setRua(txt_rua1.getText());
            pessoa.setUf(String.valueOf(cb_uf1.getSelectedItem()));
            PessoaDao pDAO = new PessoaDao();
            pDAO.update(pessoa);

            pessoaJuridica.setCnpj(jftCNPJ1.getText());
            pessoaJuridica.setNomeFantasia(txt_nomeFantasia1.getText());
            pessoaJuridica.setPessoa(pessoa);
            pessoaJuridica.setRazaoSocial(txt_razaoSocial1.getText());
            PessoaJuridicaDAO pjDAO = new PessoaJuridicaDAO();
            pjDAO.update(pessoaJuridica);

            tel.setPessoa(pessoa);
            tel.setTelefoneCelular(jftCelEmp1.getText());
            tel.setTelefoneFixo(jftTelEmp1.getText());
            TelefoneDAO telDAO = new TelefoneDAO();
            telDAO.update(tel);
             setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            //altera o cadastro da pessoa e depois exibi-se uma mensagem para o usuario
             JOptionPane.showMessageDialog(null, "Alteração do cadastro realizado com sucesso");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao inserir Cliente");
        }
        txtNumeroEmp.setEnabled(false);
        txt_bairro1.setEnabled(false);
        txt_cidade1.setEnabled(false);
        txt_emailPJ1.setEnabled(false);
        txt_nomeFantasia1.setEnabled(false);
        txt_razaoSocial1.setEnabled(false);
        txt_representante1.setEnabled(false);
        txt_rua1.setEnabled(false);
        jftCEPEmp.setEnabled(false);
        jftCNPJ1.setEnabled(false);
        jftCelEmp1.setEnabled(false);
        jftTelEmp1.setEnabled(false);
        cb_uf1.setEnabled(false);

        btnSalvarEmp.setEnabled(false);
         setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnSalvarEmpActionPerformed

    private void txtNumeroEmpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroEmpKeyTyped
        //restringe somente a inserção de caracteres numericos
        String caracteres = "0987654321";

        if (!caracteres.contains(evt.getKeyChar() + "")) {

            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroEmpKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnSalvarEmp;
    private javax.swing.JComboBox cb_uf1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JFormattedTextField jftCEPEmp;
    private javax.swing.JFormattedTextField jftCNPJ1;
    private javax.swing.JFormattedTextField jftCelEmp1;
    private javax.swing.JFormattedTextField jftTelEmp1;
    private javax.swing.JLabel lbl_bairro1;
    private javax.swing.JLabel lbl_cidade1;
    private javax.swing.JLabel lbl_cnpj1;
    private javax.swing.JLabel lbl_emailPJ1;
    private javax.swing.JLabel lbl_nomeFantasia1;
    private javax.swing.JLabel lbl_numero1;
    private javax.swing.JLabel lbl_razaoSocial1;
    private javax.swing.JLabel lbl_representante1;
    private javax.swing.JLabel lbl_uf1;
    private javax.swing.JLabel lbll_rua1;
    private javax.swing.JTextField txtNumeroEmp;
    private javax.swing.JTextField txt_bairro1;
    private javax.swing.JTextField txt_cidade1;
    private javax.swing.JTextField txt_emailPJ1;
    private javax.swing.JTextField txt_nomeFantasia1;
    private javax.swing.JTextField txt_razaoSocial1;
    private javax.swing.JTextField txt_representante1;
    private javax.swing.JTextField txt_rua1;
    // End of variables declaration//GEN-END:variables
}
